@extends('backend.main_backend')
@section('title', 'Product Data')
@section('content')
<div class="content-header"><div class="container-fluid"><div class="row mb-2"><div class="col-sm-6"><h1 class="m-0">Product Data</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-right"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Product Data</li></ol></div></div></div></div>
<section class="content"><div class="container-fluid">@include('backend.layouts.flash')<div class="card capolaga-user-card"><div class="card-header border-0"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center"><h3 class="card-title font-weight-normal">Product Master</h3><div class="capolaga-user-toolbar mt-3 mt-lg-0"><form method="GET" action="{{ route('admin.products.index') }}" class="capolaga-user-search"><div class="input-group"><input type="text" name="q" class="form-control" placeholder="Search product..." value="{{ request('q') }}"><div class="input-group-append"><button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button></div></div></form><form method="GET" action="{{ route('admin.products.index') }}"><input type="hidden" name="q" value="{{ request('q') }}"><select name="category_id" class="form-control capolaga-action-btn" onchange="this.form.submit()"><option value="">All Categories</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) request('category_id') === (string) $category->id)>{{ $category->label }}</option>@endforeach</select></form></div></div></div><div class="card-body pt-4"><div class="table-responsive"><table class="table table-bordered table-hover capolaga-user-table"><thead><tr><th>No</th><th>Product</th><th>Category</th><th>Mitra</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse ($products as $product)<tr><td>{{ $products->firstItem() + $loop->index }}</td><td><div class="font-weight-bold">{{ $product->name }}</div></td><td>{{ $product->category?->label }}</td><td>{{ $product->mitra?->business_name ?? 'Capolaga' }}</td><td>Rp {{ number_format($product->price, 0, ',', '.') }} {{ $product->price_label }}</td><td><div class="d-flex flex-wrap align-items-center" style="gap: 0.4rem;"><span class="badge badge-{{ $product->is_active ? 'success' : 'secondary' }}">{{ $product->is_active ? 'Active' : 'Inactive' }}</span>@if ($product->is_featured)<span class="badge badge-info">Featured</span>@endif</div></td><td><div class="capolaga-action-group"><a href="{{ route('admin.products.edit', $product) }}" class="btn btn-warning btn-sm capolaga-icon-btn"><i class="fas fa-edit"></i></a><form action="{{ route('admin.products.destroy', $product) }}" method="POST" class="d-inline" onsubmit="return confirm('Yakin ingin menghapus produk ini?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm capolaga-icon-btn" type="submit"><i class="fas fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted p-4">Belum ada produk.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer clearfix">{{ $products->links() }}</div></div></div></section>
@endsection




